spring:
  application:
    name: qw-ai-code-screenshot
  profiles:
    active: local
server:
  port: 8127
  servlet:
    context-path: /api
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${cos.client.host}
    secretId: ${cos.client.secret-id}
    secretKey: ${cos.client.secret-key}
    region: ${cos.client.region}
    bucket: ${cos.client.bucket-name}


# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000


