spring:
  application:
    name: qw-ai-code-user
  # session
  session:
    store-type: redis
    # 30 days expire
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qw_ai_code_mother?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hsp
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
  profiles:
    active: local
server:
  port: 8124
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.zqw.qwaicodeuser.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
